import React, { useState } from "react";
import { useParams, useNavigate } from "react-router-dom";
import { motion, AnimatePresence } from "framer-motion";
import {
  ArrowLeft,
  MapPin,
  User,
  Phone,
  Calendar,
  Clock,
  AlertTriangle,
  CheckCircle2,
  Circle,
  ChevronRight,
  FileText,
  MessageSquare,
  Activity,
  Workflow,
  Upload,
  Send,
  Building2,
  Tag,
  Hash,
  Loader2,
} from "lucide-react";
import OfficerLayout from "../../layouts/OfficerLayout";
import { PriorityBadge, StatusBadge, SLABadge } from "../../components/Badges";
import { useGrievance } from "../../hooks/useGrievances";

// ── Per-grievance timeline & action plan data ──────────────────────────────
const timelineData = {
  "GRV-1024": [
    { time: "10 May 2025, 09:30 AM", event: "Grievance submitted by citizen", type: "submitted", done: true },
    { time: "10 May 2025, 09:32 AM", event: "Triage Agent structured the complaint — Category: Water Supply, Priority: HIGH", type: "ai", done: true },
    { time: "10 May 2025, 09:35 AM", event: "Resolution plan generated by AI — 5 action steps created", type: "ai", done: true },
    { time: "10 May 2025, 10:00 AM", event: "Assigned to Rahul Sharma (Ward Officer, Ward 5)", type: "assigned", done: true },
    { time: "10 May 2025, 12:00 PM", event: "Field inspection in progress", type: "action", done: false },
    { time: "Pending", event: "Repair & upload resolution evidence", type: "pending", done: false },
    { time: "Pending", event: "Citizen verification", type: "pending", done: false },
  ],
  "GRV-1031": [
    { time: "09 May 2025, 08:00 AM", event: "Grievance submitted by citizen", type: "submitted", done: true },
    { time: "09 May 2025, 08:03 AM", event: "Triage Agent structured — Category: Road Damage, Priority: HIGH", type: "ai", done: true },
    { time: "09 May 2025, 08:10 AM", event: "Assigned to Rahul Sharma (Ward Officer, Ward 5)", type: "assigned", done: true },
    { time: "09 May 2025, 06:00 PM", event: "SLA breach — no action taken. Supervisor notified.", type: "escalation", done: true },
    { time: "10 May 2025, 09:00 AM", event: "Second escalation triggered — Executive Engineer notified.", type: "escalation", done: true },
  ],
};

const actionPlanData = {
  "GRV-1024": [
    { step: 1, title: "Verify complaint location", responsible: "Ward Officer", deadline: "4 hours", status: "Completed", dependency: null },
    { step: 2, title: "Inspect water pipeline", responsible: "Field Team", deadline: "12 hours", status: "In Progress", dependency: null },
    { step: 3, title: "Identify root cause", responsible: "Water Department", deadline: "After inspection", status: "Pending", dependency: "Inspection" },
    { step: 4, title: "Repair the fault", responsible: "Maintenance Team", deadline: "After cause identified", status: "Pending", dependency: "Root cause" },
    { step: 5, title: "Upload resolution evidence (before & after)", responsible: "Field Officer", deadline: "After repair", status: "Pending", dependency: "Repair" },
  ],
  "GRV-1031": [
    { step: 1, title: "Inspect damaged road section", responsible: "Field Team", deadline: "6 hours", status: "Overdue", dependency: null },
    { step: 2, title: "Estimate repair scope & cost", responsible: "Roads Department", deadline: "After inspection", status: "Overdue", dependency: "Inspection" },
    { step: 3, title: "Initiate repair work", responsible: "Maintenance Team", deadline: "After estimate", status: "Pending", dependency: "Estimate" },
    { step: 4, title: "Upload photographic evidence", responsible: "Field Officer", deadline: "After repair", status: "Pending", dependency: "Repair" },
  ],
};

const TABS = ["Details", "Timeline", "Action Plan", "History"];

const timelineIconMap = {
  submitted: { icon: FileText, color: "text-blue-600", bg: "bg-blue-100", border: "border-blue-200" },
  ai: { icon: Activity, color: "text-violet-600", bg: "bg-violet-100", border: "border-violet-200" },
  assigned: { icon: User, color: "text-slate-600", bg: "bg-slate-100", border: "border-slate-200" },
  action: { icon: Workflow, color: "text-amber-600", bg: "bg-amber-100", border: "border-amber-200" },
  pending: { icon: Circle, color: "text-slate-300", bg: "bg-white", border: "border-slate-200" },
  escalation: { icon: AlertTriangle, color: "text-red-600", bg: "bg-red-100", border: "border-red-200" },
};

const actionStepStatus = {
  Completed: { bg: "bg-emerald-50", text: "text-emerald-700", border: "border-emerald-200", icon: CheckCircle2, iconColor: "text-emerald-500" },
  "In Progress": { bg: "bg-blue-50", text: "text-blue-700", border: "border-blue-200", icon: Activity, iconColor: "text-blue-500" },
  Pending: { bg: "bg-slate-50", text: "text-slate-500", border: "border-slate-200", icon: Circle, iconColor: "text-slate-300" },
  Overdue: { bg: "bg-red-50", text: "text-red-700", border: "border-red-200", icon: AlertTriangle, iconColor: "text-red-500" },
};

export default function ComplaintDetails() {
  const { id } = useParams();
  const navigate = useNavigate();
  const [activeTab, setActiveTab] = useState("Details");
  const [note, setNote] = useState("");

  const { grievance: complaint, loading, error } = useGrievance(id);
  const timeline = timelineData[id] || timelineData["GRV-1024"];
  const actionPlan = actionPlanData[id] || actionPlanData["GRV-1024"];

  if (loading) {
    return (
      <OfficerLayout>
        <div className="flex items-center justify-center h-64">
          <Loader2 className="h-8 w-8 animate-spin text-blue-600" />
        </div>
      </OfficerLayout>
    );
  }

  if (error || !complaint) {
    return (
      <OfficerLayout>
        <div className="flex flex-col items-center justify-center h-64 text-slate-400">
          <FileText className="h-12 w-12 mb-3 text-slate-200" />
          <div className="font-medium text-slate-500">{error || 'Grievance not found'}</div>
          <button onClick={() => navigate("/officer/complaints")} className="mt-3 text-sm text-blue-600 hover:underline">
            ← Back to All Complaints
          </button>
        </div>
      </OfficerLayout>
    );
  }

  return (
    <OfficerLayout>
      {/* Back */}
      <button
        onClick={() => navigate("/officer/complaints")}
        className="flex items-center gap-1.5 text-sm text-slate-500 hover:text-blue-700 mb-5 transition-colors"
      >
        <ArrowLeft size={15} /> Back to All Complaints
      </button>

      {/* Page Header */}
      <motion.div
        initial={{ opacity: 0, y: 12 }}
        animate={{ opacity: 1, y: 0 }}
        className="bg-white border border-slate-200 rounded-xl shadow-sm mb-5 overflow-hidden"
      >
        {/* Top color strip for overdue/critical */}
        {(complaint.slaStatus === "overdue" || complaint.slaStatus === "critical") && (
          <div className={`h-1 w-full ${complaint.slaStatus === "overdue" ? "bg-red-500" : "bg-amber-400"}`} />
        )}

        <div className="p-6">
          <div className="flex flex-col sm:flex-row sm:items-start sm:justify-between gap-4">
            <div className="flex-1 min-w-0">
              {/* Breadcrumb */}
              <div className="flex items-center gap-1.5 text-xs text-slate-400 mb-2">
                <span>Officer Portal</span>
                <ChevronRight size={12} />
                <span>All Complaints</span>
                <ChevronRight size={12} />
                <span className="text-blue-600 font-semibold">{complaint.id}</span>
              </div>

              <h2 className="text-xl font-bold text-slate-900 leading-snug">{complaint.title}</h2>

              <div className="flex flex-wrap items-center gap-3 mt-3">
                <StatusBadge status={complaint.status} />
                <PriorityBadge priority={complaint.priority} />
                <SLABadge slaRemaining={complaint.slaRemaining} slaStatus={complaint.slaStatus} />
              </div>
            </div>

            {/* Actions */}
            <div className="flex gap-2 flex-shrink-0">
              <button
                onClick={() => navigate("/officer/evidence")}
                className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-slate-100 hover:bg-slate-200 text-slate-700 transition-colors"
              >
                <Upload size={15} /> Upload Evidence
              </button>
              <button
                onClick={() => navigate("/officer/escalations")}
                className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-red-50 hover:bg-red-100 text-red-700 border border-red-200 transition-colors"
              >
                <AlertTriangle size={15} /> Escalate
              </button>
              <button className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-blue-700 hover:bg-blue-800 text-white transition-colors">
                <CheckCircle2 size={15} /> Mark Resolved
              </button>
            </div>
          </div>
        </div>

        {/* Tabs */}
        <div className="flex border-t border-slate-100 px-6">
          {TABS.map((tab) => (
            <button
              key={tab}
              onClick={() => setActiveTab(tab)}
              className={`relative py-3 px-4 text-sm font-medium transition-colors ${
                activeTab === tab
                  ? "text-blue-700"
                  : "text-slate-500 hover:text-slate-700"
              }`}
            >
              {tab}
              {activeTab === tab && (
                <motion.div
                  layoutId="tab-underline"
                  className="absolute bottom-0 left-0 right-0 h-0.5 bg-blue-700 rounded-t"
                />
              )}
            </button>
          ))}
        </div>
      </motion.div>

      {/* Tab Content */}
      <AnimatePresence mode="wait">
        <motion.div
          key={activeTab}
          initial={{ opacity: 0, y: 8 }}
          animate={{ opacity: 1, y: 0 }}
          exit={{ opacity: 0, y: -8 }}
          transition={{ duration: 0.18 }}
        >
          {/* ── DETAILS TAB ───────────────────────────────────────────── */}
          {activeTab === "Details" && (
            <div className="grid grid-cols-1 lg:grid-cols-3 gap-5">
              {/* Left: Main Details */}
              <div className="lg:col-span-2 space-y-5">
                {/* Description */}
                <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
                  <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wide mb-3">Grievance Description</h3>
                  <p className="text-slate-800 leading-relaxed">{complaint.description}</p>
                </div>

                {/* Evidence Attachments */}
                <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
                  <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wide mb-3">Attachments</h3>
                  {complaint.evidence_urls && complaint.evidence_urls.length > 0 ? (
                    <div className="grid grid-cols-2 gap-4">
                      {complaint.evidence_urls.map((url, i) => (
                        <div key={i} className="rounded-lg overflow-hidden border border-slate-200 aspect-video bg-slate-100">
                          <img src={url} alt={`Evidence ${i + 1}`} className="w-full h-full object-cover" />
                        </div>
                      ))}
                    </div>
                  ) : (
                    <div className="border-2 border-dashed border-slate-200 rounded-lg p-8 flex flex-col items-center justify-center text-slate-400">
                      <Upload className="h-8 w-8 mb-2 text-slate-300" />
                      <p className="text-sm">No attachments submitted by citizen</p>
                    </div>
                  )}
                </div>

                {/* Officer Note */}
                <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6">
                  <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wide mb-3">Add Officer Note</h3>
                  <textarea
                    value={note}
                    onChange={(e) => setNote(e.target.value)}
                    rows={3}
                    placeholder="Add an internal note about this case…"
                    className="w-full text-sm border border-slate-200 rounded-lg px-4 py-3 focus:outline-none focus:ring-2 focus:ring-blue-500 focus:border-transparent placeholder:text-slate-400 resize-none"
                  />
                  <div className="flex justify-end mt-3">
                    <button
                      disabled={!note.trim()}
                      className="flex items-center gap-2 px-4 py-2 rounded-lg text-sm font-semibold bg-blue-700 text-white hover:bg-blue-800 disabled:opacity-40 disabled:cursor-not-allowed transition-all"
                    >
                      <Send size={14} /> Save Note
                    </button>
                  </div>
                </div>
              </div>

              {/* Right: Metadata */}
              <div className="space-y-5">
                {/* Grievance Info */}
                <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-5">
                  <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wide mb-4">Case Information</h3>
                  <div className="space-y-3.5">
                    {[
                      { icon: Hash, label: "Grievance ID", value: complaint.id, highlight: true },
                      { icon: Tag, label: "Category", value: complaint.category },
                      { icon: Building2, label: "Department", value: complaint.category },
                      { icon: MapPin, label: "Location", value: complaint.location },
                      { icon: Calendar, label: "Submitted", value: complaint.submitted },
                      { icon: User, label: "Assigned To", value: complaint.assignedTo },
                    ].map(({ icon: Icon, label, value, highlight }) => (
                      <div key={label} className="flex items-start gap-3">
                        <div className="mt-0.5 p-1.5 bg-slate-50 rounded-md border border-slate-100 flex-shrink-0">
                          <Icon className="h-3.5 w-3.5 text-slate-400" />
                        </div>
                        <div className="min-w-0">
                          <div className="text-xs text-slate-400 mb-0.5">{label}</div>
                          <div className={`text-sm font-semibold truncate ${highlight ? "text-blue-700" : "text-slate-800"}`}>
                            {value}
                          </div>
                        </div>
                      </div>
                    ))}
                  </div>
                </div>

                {/* Citizen Info */}
                <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-5">
                  <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wide mb-4">Citizen Information</h3>
                  <div className="flex items-center gap-3 mb-4">
                    <div className="w-10 h-10 rounded-full bg-slate-200 flex items-center justify-center text-slate-600 font-bold text-sm flex-shrink-0">
                      {complaint.citizen.charAt(0)}
                    </div>
                    <div>
                      <div className="text-sm font-semibold text-slate-800">{complaint.citizen}</div>
                      <div className="text-xs text-slate-400">{complaint.location}</div>
                    </div>
                  </div>
                  <div className="flex items-center gap-2 text-sm text-slate-600">
                    <Phone size={14} className="text-slate-400" />
                    {complaint.phone}
                  </div>
                </div>

                {/* SLA Box */}
                <div className={`rounded-xl border p-5 ${
                  complaint.slaStatus === "overdue"
                    ? "bg-red-50 border-red-200"
                    : complaint.slaStatus === "critical"
                    ? "bg-amber-50 border-amber-200"
                    : "bg-slate-50 border-slate-200"
                }`}>
                  <div className="flex items-center gap-2 mb-2">
                    <Clock className={`h-4 w-4 ${
                      complaint.slaStatus === "overdue" ? "text-red-600"
                      : complaint.slaStatus === "critical" ? "text-amber-600"
                      : "text-slate-500"
                    }`} />
                    <h3 className="text-sm font-bold text-slate-700">SLA Status</h3>
                  </div>
                  <div className={`text-2xl font-bold mb-1 ${
                    complaint.slaStatus === "overdue" ? "text-red-700"
                    : complaint.slaStatus === "critical" ? "text-amber-700"
                    : "text-slate-700"
                  }`}>
                    {complaint.slaRemaining}
                  </div>
                  {complaint.slaStatus === "overdue" && (
                    <p className="text-xs text-red-600 mt-1">SLA breached. Supervisor has been notified.</p>
                  )}
                  {complaint.slaStatus === "critical" && (
                    <p className="text-xs text-amber-600 mt-1">Deadline approaching. Immediate action required.</p>
                  )}
                </div>
              </div>
            </div>
          )}

          {/* ── TIMELINE TAB ───────────────────────────────────────────── */}
          {activeTab === "Timeline" && (
            <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6 max-w-3xl">
              <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wide mb-6">Case Timeline</h3>
              <div className="relative pl-4 border-l-2 border-slate-100 space-y-8">
                {(() => {
                  const events = [];
                  const timeStr = complaint.submitted; // Formatted date string
                  
                  // 1. Submitted
                  events.push({
                    time: timeStr,
                    event: "Grievance submitted by citizen",
                    type: "submitted",
                    done: true
                  });
                  
                  // 2. Triage
                  if (complaint.ai_triage_data) {
                    events.push({
                      time: timeStr,
                      event: `Triage Agent structured the complaint — Category: ${complaint.ai_triage_data.category}, Priority: ${complaint.ai_triage_data.priority}`,
                      type: "ai",
                      done: true
                    });
                  }
                  
                  // 3. Workflow
                  if (complaint.ai_workflow) {
                    events.push({
                      time: timeStr,
                      event: `Resolution plan generated by AI — ${complaint.ai_workflow.tasks.length} action steps created`,
                      type: "ai",
                      done: true
                    });
                  }
                  
                  // 4. Evidence
                  if (complaint.ai_evidence_report) {
                    events.push({
                      time: timeStr, // We don't have exact evidence timestamp yet, using submitted for demo
                      event: `Evidence Agent analyzed resolution photos (Confidence: ${complaint.ai_evidence_report.confidence}%)`,
                      type: "ai",
                      done: true
                    });
                  }
                  
                  // 5. Verdict
                  if (complaint.ai_verdict) {
                    events.push({
                      time: timeStr,
                      event: `Resolution Agent marked case as ${complaint.ai_verdict}`,
                      type: "ai",
                      done: true
                    });
                  }
                  
                  if (!complaint.ai_verdict) {
                    events.push({
                      time: "Pending",
                      event: "Awaiting resolution & evidence upload",
                      type: "pending",
                      done: false
                    });
                  }

                  return events.map((item, i) => {
                    const cfg = timelineIconMap[item.type] || timelineIconMap.pending;
                    return (
                      <div key={i} className="relative">
                        <div className={`absolute -left-[29px] top-1 h-6 w-6 rounded-full border-2 border-white flex items-center justify-center ${cfg.bg} ${item.done ? '' : 'opacity-50'}`}>
                          <cfg.icon className={`h-3 w-3 ${cfg.color}`} />
                        </div>
                        <div>
                          <p className={`text-sm ${item.done ? 'font-semibold text-slate-800' : 'text-slate-500'}`}>{item.event}</p>
                          <p className="text-xs text-slate-400 mt-1">{item.time}</p>
                        </div>
                      </div>
                    );
                  });
                })()}
              </div>
            </div>
          )}

          {/* ── ACTION PLAN TAB ───────────────────────────────────────────── */}
          {activeTab === "Action Plan" && (
            <div className="bg-white border border-slate-200 rounded-xl shadow-sm overflow-hidden">
              <div className="px-6 py-5 border-b border-slate-200 bg-slate-50 flex items-center justify-between">
                <div>
                  <h3 className="font-bold text-slate-900">AI-Generated Action Plan</h3>
                  <p className="text-xs text-slate-500 mt-0.5">Generated by Resolution Planner Agent · llama-3.3-70b-versatile</p>
                </div>
                <div className="px-3 py-1 bg-violet-100 text-violet-700 text-xs font-bold rounded-full">
                  AI Generated
                </div>
              </div>
              <div className="p-6">
                {!complaint.ai_workflow ? (
                  <div className="text-center py-8 text-slate-500">
                    <Activity className="h-8 w-8 mx-auto text-slate-300 mb-3" />
                    <p>No AI Action Plan generated yet.</p>
                  </div>
                ) : (
                  <div className="space-y-6">
                    {complaint.ai_workflow.tasks.map((step, i) => {
                      // Mocking status based on array index for demo if not available
                      const status = i === 0 ? "Completed" : i === 1 ? "In Progress" : "Pending";
                      const cfg = actionStepStatus[status] || actionStepStatus.Pending;
                      return (
                        <div key={i} className="flex gap-4">
                          <div className="mt-1 h-8 w-8 rounded-full bg-slate-100 border border-slate-200 flex items-center justify-center text-sm font-bold text-slate-500 flex-shrink-0">
                            {i + 1}
                          </div>
                          <div className="flex-1 pb-6 border-b border-slate-100 last:border-0 last:pb-0">
                            <div className="flex items-center justify-between mb-1">
                              <div className="flex items-center gap-3">
                                <h4 className="font-bold text-slate-800 text-sm">{step.title}</h4>
                                <span className={`text-[10px] font-bold px-2 py-0.5 rounded uppercase tracking-wider ${cfg.bg} ${cfg.text} ${cfg.border} border`}>
                                  {status}
                                </span>
                              </div>
                              <cfg.icon className={`h-4 w-4 ${cfg.iconColor}`} />
                            </div>
                            <div className="flex items-center gap-4 text-xs text-slate-500 mt-2 flex-wrap">
                              <span className="flex items-center gap-1"><User size={12} /> {step.department || "Field Team"}</span>
                            </div>
                          </div>
                        </div>
                      );
                    })}
                  </div>
                )}
              </div>
              <div className="bg-slate-50 px-6 py-4 border-t border-slate-200">
                <button className="text-sm font-semibold text-blue-700 hover:underline flex items-center gap-1.5">
                  <Workflow size={14} /> Update Action Status
                </button>
              </div>
            </div>
          )}

          {/* ── HISTORY TAB ───────────────────────────────────────────── */}
          {activeTab === "History" && (
            <div className="bg-white border border-slate-200 rounded-xl shadow-sm p-6 max-w-2xl">
              <h3 className="text-sm font-bold text-slate-500 uppercase tracking-wide mb-4">Case History & Audit Log</h3>
              <div className="space-y-3">
                {[
                  { action: "Status updated to In Progress", by: "Rahul Sharma", time: "10 May 2025, 10:05 AM" },
                  { action: "Case assigned to Rahul Sharma", by: "System (Auto)", time: "10 May 2025, 09:35 AM" },
                  { action: "Action plan generated by AI", by: "Resolution Planner Agent", time: "10 May 2025, 09:32 AM" },
                  { action: "Complaint triaged and structured", by: "Triage Agent", time: "10 May 2025, 09:30 AM" },
                  { action: "Complaint submitted by citizen", by: complaint.citizen, time: complaint.submitted },
                ].map((entry, idx) => (
                  <motion.div
                    key={idx}
                    initial={{ opacity: 0 }}
                    animate={{ opacity: 1 }}
                    transition={{ delay: idx * 0.06 }}
                    className="flex items-start justify-between gap-4 py-3 border-b border-slate-50 last:border-0"
                  >
                    <div>
                      <div className="text-sm font-medium text-slate-800">{entry.action}</div>
                      <div className="text-xs text-slate-400 mt-0.5">by {entry.by}</div>
                    </div>
                    <div className="text-xs text-slate-400 flex-shrink-0">{entry.time}</div>
                  </motion.div>
                ))}
              </div>
            </div>
          )}
        </motion.div>
      </AnimatePresence>
    </OfficerLayout>
  );
}
